//
// Created by hscloud on 26. 7. 7.
//

#pragma once

#if defined(_WIN32)

#include <winsock2.h>
#include <ws2def.h>
#include <mswsock.h>
#include <windows.h>

#ifndef WSAID_MULTIPLE_RIO

typedef struct RIO_BUFFERID_t* RIO_BUFFERID,** PRIO_BUFFERID;
typedef struct RIO_CQ_t* RIO_CQ,** PRIO_CQ;
typedef struct RIO_RQ_t* RIO_RQ,** PRIO_RQ;

#define RIO_INVALID_BUFFERID ((RIO_BUFFERID)0xFFFFFFFF)
#define RIO_INVALID_CQ       ((RIO_CQ)0)
#define RIO_INVALID_RQ       ((RIO_RQ)0)
#define RIO_MAX_CQ_SIZE      0x8000000
#define RIO_CORRUPT_CQ       0xFFFFFFFF

typedef struct _RIORESULT
{
	LONG Status;
	ULONG BytesTransferred;
	ULONGLONG SocketContext;
	ULONGLONG RequestContext;
} RIORESULT,* PRIORESULT;

typedef struct _RIO_BUF
{
	RIO_BUFFERID BufferId;
	ULONG Offset;
	ULONG Length;
} RIO_BUF,* PRIO_BUF;

typedef enum _RIO_NOTIFICATION_COMPLETION_TYPE
{
	RIO_EVENT_COMPLETION = 1,
	RIO_IOCP_COMPLETION  = 2,
} RIO_NOTIFICATION_COMPLETION_TYPE;

typedef struct _RIO_NOTIFICATION_COMPLETION
{
	RIO_NOTIFICATION_COMPLETION_TYPE Type;

	union
	{
		struct
		{
			HANDLE EventHandle;
			BOOL NotifyReset;
		} Event;

		struct
		{
			HANDLE IocpHandle;
			PVOID CompletionKey;
			PVOID Overlapped;
		} Iocp;
	};
} RIO_NOTIFICATION_COMPLETION,* PRIO_NOTIFICATION_COMPLETION;

typedef BOOL (WINAPI*LPFN_RIORECEIVE)(RIO_RQ, PRIO_BUF, ULONG, DWORD, PVOID);
typedef int (WINAPI*LPFN_RIORECEIVEEX)(RIO_RQ, PRIO_BUF, ULONG, PRIO_BUF, PRIO_BUF, PRIO_BUF, PRIO_BUF, DWORD, PVOID);
typedef BOOL (WINAPI*LPFN_RIOSEND)(RIO_RQ, PRIO_BUF, ULONG, DWORD, PVOID);
typedef int (WINAPI*LPFN_RIOSENDEX)(RIO_RQ, PRIO_BUF, ULONG, PRIO_BUF, PRIO_BUF, PRIO_BUF, PRIO_BUF, DWORD, PVOID);
typedef VOID (WINAPI*LPFN_RIOCLOSECOMPLETIONQUEUE)(RIO_CQ);
typedef RIO_CQ (WINAPI*LPFN_RIOCREATECOMPLETIONQUEUE)(DWORD, PRIO_NOTIFICATION_COMPLETION);
typedef RIO_RQ (WINAPI*LPFN_RIOCREATEREQUESTQUEUE)(SOCKET, ULONG, ULONG, ULONG, ULONG, RIO_CQ, RIO_CQ, PVOID);
typedef ULONG (WINAPI*LPFN_RIODEQUEUECOMPLETION)(RIO_CQ, PRIORESULT, ULONG);
typedef VOID (WINAPI*LPFN_RIODEREGISTERBUFFER)(RIO_BUFFERID);
typedef INT (WINAPI*LPFN_RIONOTIFY)(RIO_CQ);
typedef RIO_BUFFERID (WINAPI*LPFN_RIOREGISTERBUFFER)(PCHAR, DWORD);
typedef BOOL (WINAPI*LPFN_RIORESIZECOMPLETIONQUEUE)(RIO_CQ, DWORD);
typedef BOOL (WINAPI*LPFN_RIORESIZEREQUESTQUEUE)(RIO_RQ, DWORD, DWORD);

typedef struct _RIO_EXTENSION_FUNCTION_TABLE
{
	DWORD cbSize;
	LPFN_RIORECEIVE RIOReceive;
	LPFN_RIORECEIVEEX RIOReceiveEx;
	LPFN_RIOSEND RIOSend;
	LPFN_RIOSENDEX RIOSendEx;
	LPFN_RIOCLOSECOMPLETIONQUEUE RIOCloseCompletionQueue;
	LPFN_RIOCREATECOMPLETIONQUEUE RIOCreateCompletionQueue;
	LPFN_RIOCREATEREQUESTQUEUE RIOCreateRequestQueue;
	LPFN_RIODEQUEUECOMPLETION RIODequeueCompletion;
	LPFN_RIODEREGISTERBUFFER RIODeregisterBuffer;
	LPFN_RIONOTIFY RIONotify;
	LPFN_RIOREGISTERBUFFER RIORegisterBuffer;
	LPFN_RIORESIZECOMPLETIONQUEUE RIOResizeCompletionQueue;
	LPFN_RIORESIZEREQUESTQUEUE RIOResizeRequestQueue;
} RIO_EXTENSION_FUNCTION_TABLE,* PRIO_EXTENSION_FUNCTION_TABLE;

#define WSAID_MULTIPLE_RIO \
	{ 0x8509e081, 0x96dd, 0x4005, { 0xb1, 0x65, 0x9e, 0x2e, 0xe8, 0xc7, 0x9e, 0x3f } }

#endif // WSAID_MULTIPLE_RIO

#ifndef SIO_GET_MULTIPLE_EXTENSION_FUNCTION_POINTERS
#define SIO_GET_MULTIPLE_EXTENSION_FUNCTION_POINTERS _WSAIORW(IOC_WS2, 36)
#endif

#endif // _WIN32
